static/js/app.js
In the Query tab, only run the selected text. If nothing selected, run all text in the editor.
=> Run selected text. Implements sosedoff/pgweb#78.

app.json
1. Consider using the secret generator so that deploys don't default to a known secret.
2. tag it with golang
=> Some app.json updates to consider

pkg/client/client.go
=> Return number of affected rows if sql query is update or delete

static/css/app.css
Fix https://github.com/sosedoff/pgweb/issues/140
=> Table Information no vertical scroll bar

pkg/api/helpers.go
Noticed a typo while going through code.
=> A small typo fix

pkg/client/result.go
=> Specify cell timestamp layout for CSV export, #163

static/js/app.js
Created a clean PR without the feature change.
=> Fixed broken export to CSV/JSON/XML if hashmark in URL

data/booktown.sql, pkg/client/client.go, pkg/client/client_test.go
Fixes issues with case-sensitivity in order statements
=> Add escaping to order statement

pkg/api/api.go
=> Fix path rewrite on DB change

Makefile
There were two lines for `make test` in the Makefile.
=> Removed duplicate usage line in Makefile.

Dockerfile
Subj. Will need to check the image size as well to make sure it's as thin as the current one.
=> Use alpine:3.6 as a docker base image

pkg/cli/cli.go, pkg/client/client.go
=> Print postgres version on start in a single-session mode

pkg/client/client.go, pkg/command/options.go
=> Add new CLI option to disable SSH connections

static/index.html, static/js/app.js
#301 
- Added "Copy Table Name" to menu for table names
- Added copy to clipboard with original project function & regexp for filtering table namespace
- Changed some tabs in indent to spaces
- Deleted some trailing whitespaces
=> added simple copy to clipboard from data-id prop

README.md
I think it's good idea - add some useful badges
=> Update README - add more badges

pkg/bookmarks/bookmarks.go
https://www.postgresql.org/docs/9.1/static/libpq-ssl.html
=> Fix sslmode typo

pkg/api/middleware.go, pkg/api/routes.go, pkg/command/options.go
=> Add support for CORS

.travis.yml, pkg/client/client_test.go, pkg/statements/sql.go
=> Include constraint name under "constraints" tab

pkg/cli/cli.go, pkg/client/client.go, pkg/connection/connection_string.go, pkg/connection/connection_string_test.go
=> Fix issues with connection string builder

pkg/api/api.go, pkg/api/backend.go, pkg/api/helpers.go, pkg/api/helpers_test.go, pkg/api/middleware.go, pkg/api/session_cleanup.go, pkg/client/tunnel.go, pkg/connection/port.go, pkg/connection/port_test.go
=> Cleanup and refactor

pkg/cli/cli.go
=> Fix startup error when DATABASE_URL is set

pkg/client/client.go, pkg/client/client_test.go, pkg/statements/sql.go
This should address #412, #413
=> Fix estimation for camelcase schemas

pkg/client/client.go, pkg/client/client_test.go, pkg/client/util.go
Another guard in case if `default_transaction_read_only` gets changed back.
=> Keyword restriction in read-only mode

pkg/client/dump.go, pkg/client/dump_test.go
=> Drop unsupported pg_dump options from connection string

pkg/api/api.go
=> Do not show other databases if session is locked

Makefile
Please add the `hacktoberfest` label 😄 
- Add `-s -w` to strip the debugging information.
- Remove darwin/386 target.
Before (using golang 1.1.5.2):
```
ls -lah bin
total 255720
drwxr-xr-x  14 allisson  staff   448B Oct 10 11:51 .
drwxr-xr-x  29 allisson  staff   928B Oct 10 11:49 ..
-rwxr-xr-x   1 allisson  staff    14M Oct 10 11:51 pgweb_darwin_amd64
-rw-r--r--   1 allisson  staff   7.0M Oct 10 11:51 pgweb_darwin_amd64.zip
-rwxr-xr-x   1 allisson  staff    12M Oct 10 11:51 pgweb_linux_386
-rw-r--r--   1 allisson  staff   6.8M Oct 10 11:51 pgweb_linux_386.zip
-rwxr-xr-x   1 allisson  staff    14M Oct 10 11:51 pgweb_linux_amd64
-rw-r--r--   1 allisson  staff   7.0M Oct 10 11:51 pgweb_linux_amd64.zip
-rwxr-xr-x   1 allisson  staff    12M Oct 10 11:51 pgweb_linux_arm_v5
-rw-r--r--   1 …
```
=> feat(release): strip binary to reduce size

static/index.html
Removes the pesky autocomplete artifact on the database search field - we already have autocomplete powered by the js
=> Disable autocomplete on database search field

pkg/cli/cli.go
=> Use regular expression for checking some of the connection errors

pkg/client/dump_test.go
This is currently failing on localhost
=> Adjust error message matching for dump spec

Makefile
Adds a new binary target, per #512
=> Add darwin/arm64 binary build target

Dockerfile
alpine:3.14 is the latest alpine image
=> chore: update image to use `alpine:3.14`

pkg/api/api.go, pkg/api/routes.go, static/css/app.css, static/index.html, static/js/app.js, static/js/bootstrap-dropdown.js
Addresses the issue I raised in #518. Happy to explore different UX directions and/or button labels if the current design is not desirable.
I have had to bring in the bootstrap 3.2.0 dropdown plugin from [here](https://github.com/twbs/bootstrap/blob/v3.2.0/js/dropdown.js). Code is licensed under MIT and retains its attribution.
=> Explain analyze dropdown button (issue #518)

pkg/api/api.go
Addresses https://github.com/sosedoff/pgweb/issues/542. Test coverage will be supplied in a different PR.
=> Use HTTP 302 status code for successful backend redirect

static/js/app.js
Implements https://github.com/sosedoff/pgweb/issues/482
=> Auto-detect the query from the query source based on user selection

Makefile, script/build_all.sh
=> Replace gox with a bash build script

Dockerfile
=> Install latest postgres client

.github/workflows/checks.yml, Makefile, pkg/api/api.go, pkg/api/backend_test.go, pkg/bookmarks/bookmarks.go, pkg/cli/cli.go, pkg/client/client_test.go, pkg/client/result.go, pkg/client/tunnel.go, pkg/connection/port.go
This codebase is pretty old and has tons of inefficient code, adding linter should partially help with keeping the code in check.
=> Configure linter runs

go.mod, go.sum, pkg/command/options.go
=> Add support for PGWEB_ prefix environment variables

static/js/app.js
Should fix #587 and clean up code a bit.
=> Refactor data export js functionality

Makefile
These will be necessary for github actions release
=> Set LDFLAGS for make build/release commands

static/css/app.css, static/index.html, static/js/app.js
Adds ability to:
- View view/mat.view definition in structure via context menu
- Copy view name via context menu
=> Add ability to view and copy views/materialized views definitions

static/css/app.css, static/index.html, static/js/app.js
Long awaited query box resizing feature. This will also persist the height into sessionStorage
=> Make query input box resizable

.github/workflows/checks.yml, go.mod, go.sum, pkg/api/api.go, pkg/api/errors.go, pkg/api/helpers.go, pkg/api/helpers_test.go, pkg/bookmarks/bookmarks.go, pkg/cli/cli.go, pkg/client/client.go, pkg/client/dump.go, pkg/client/dump_test.go, pkg/client/tunnel.go, pkg/client/util.go, pkg/client/util_test.go
This should eliminate hard to debug issues when pg_dump is not compatible with server version.
=> Perform client version validation before executing pg_dump command

.github/workflows/checks.yml, data/booktown.sql, docker-compose-pg.yml, pkg/client/client_test.go, pkg/statements/sql/function.sql, pkg/statements/sql/objects.sql
Should cover all versions from 9.6-15 to catch unexpected bugs
Also adds local docker compose to quickly spin up all test versions in docker.
=> Improved Pg test matrix

pkg/command/options.go, pkg/connection/connection_string.go, pkg/connection/connection_string_test.go
=> Add default connect_timeout option to connection string

static/js/app.js
=> Fix bookmarks ID check

static/css/app.css, static/index.html, static/js/app.js
=> Show error message when API calls fail

docker-compose.yml
`DATABASE_URL` has been deprecated
=> Replace DATABASE_URL with PGWEB_DATABASE_URL

pkg/statements/sql/objects.sql
This is a regression from #608
=> ensure that objects are sorted by schema and name

static/index.html
=> Fix connection window layout on smaller viewports

pkg/command/options.go
`import (
"github.com/sosedoff/pgweb/pkg/cli"
"os"
)
func main() {
os.Setenv("PGWEB_URL_PREFIX", "prefix/pgWeb")
cli.Run()
}`
=> fix when the prefix has a '/' and it is not ended with '/'

pkg/api/api.go, pkg/client/client.go
=> Fix unclosed database sessions and tunnels

pkg/client/util.go
=> Add UPDATE to list of restricted keywords in read-only mode

static/index.html, static/js/app.js
Adds a new context menu item to run `ANALYZE TABLE <...>` quickly.
=> Add analyze table action

.github/workflows/checks.yml, .github/workflows/deploy.yml, .github/workflows/docker.yml, README.md
Prep PR to swap the master -> main branch
=> Update references from master branch to main branch

.github/workflows/checks.yml
Adds PostgreSQL 17 to list of tested versions
=> Try running checks against pg 17

pkg/api/api.go, pkg/api/routes.go, pkg/client/client.go, pkg/client/client_test.go, pkg/statements/sql.go, pkg/statements/sql/settings.sql, static/index.html, static/js/app.js
Adds a new view to list all server settings.
=> Add server settings view
